<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RFID125k.Core\RFID125k.Core.csproj" />
    <None Include="..\vendor\*.dll" Link="%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="rfid125k.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\python\lang.*.json" Link="%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\rfid125k.ico" Link="rfid125k.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>..\rfid125k.ico</ApplicationIcon>
  </PropertyGroup>

</Project>